/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class ExerciseQueueTest {
    @Test public void testSomeLibraryMethod() {
        ExerciseQueue classUnderTest = new ExerciseQueue();
        assertTrue("someLibraryMethod should return 'true'", 
            classUnderTest.someLibraryMethod());
    }
}
